import './globals.css';
import type { Metadata } from 'next';
import { Chakra_Petch } from 'next/font/google';
import NextAuthProvider from './util/auth';

const inter = Chakra_Petch({ weight: '400', preload: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body className={inter.className}>{children}</body>
      </NextAuthProvider>
    </html>
  );
}
